apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-apps
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: devops/argo/applications
    repoURL: 'https://github.com/danduh/tvflix.git'
    targetRevision: 'lessons/part-7'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


