apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tvflix-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true

  source:
    path: devops/argo/applications/tvflix
    repoURL: https://github.com/danduh/tvflix
    targetRevision: argo
