apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tvflix-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: devops/argo/applications/tvflix
    repoURL: https://github.com/danduh/tvflix.git
    targetRevision: devops/argo
