apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tvflix-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true

  source:
    path: argo/be-charts/tvflix-ui
    repoURL: https://github.com/danduh/tvflix
    targetRevision: {{ .Values.platform_branch }}
    helm:
      valueFiles:
        - ../../values-{{ .Values.cluster_name }}.yaml

