apiVersion: v1
kind: ConfigMap
metadata:
  name: gql-config
#  namespace: default
data:
  gql-config.json: |
    {
      "subgraphs": [
        { "name": "person", "url": "http://cast-gql:{{ .Values.gqlServices.castGql.port }}" }
      ]
    }
